on:
  push:
  pull_request:

name: build_singularity

jobs:
  build_singularity:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Build Container
        run: cd singularity; ./run_singularity.sh

